### ISSUE TITLE
Reference

### ISSUE THREAD

**Issue by andreasernst** [deltatree/qrsct#1]
Hi,

i was testing the GiroCode, but i get every time as reference OTHR with the Sparkassen iOS App.

Andreas

**Comment by andreasernst** [comment]
Class QRSCT

these lines causes the issue ( 68 and 69 )

//		data.append(this.purpose.getPurposeId()); // 4 - (Geschäftscode)
//		data.append("\n"); //$NON-NLS-1$

**Comment by deltatree** [comment]
Hi Andreas, Deinen Fehler konnten wir leider nicht nachstellen - Der generierte Text ist korrekt - wahrscheinlich liegt der Fehler in der App: tritt dieser noch auf?

Hier wird der Aufbau gut beschrieben: https://de.m.wikipedia.org/wiki/EPC-QR-Code
